In [8]:
import pandas as pd
import numpy as np
import sqlite3

In [10]:
connection = sqlite3.connect("RecruitSmart.db")

cursor = connection.cursor()

print("Database Created Successfully!")

Database Created Successfully!

In [12]:
jobs = pd.read_csv(r"C:\Users\cbala\OneDrive\Desktop\RecruitSmart\data\jobs_cleaned.csv")

people = pd.read_csv(r"C:\Users\cbala\OneDrive\Desktop\RecruitSmart\data\01_people.csv")

applications = pd.read_csv(r"C:\Users\cbala\OneDrive\Desktop\RecruitSmart\data\applications.csv")

person_skills = pd.read_csv(r"C:\Users\cbala\OneDrive\Desktop\RecruitSmart\data\05_person_skills.csv")

skills = pd.read_csv(r"C:\Users\cbala\OneDrive\Desktop\RecruitSmart\data\06_skills.csv")

In [14]:
jobs.to_sql("Jobs", connection, if_exists="replace", index=False)

people.to_sql("Candidates", connection, if_exists="replace", index=False)

applications.to_sql("Applications", connection, if_exists="replace", index=False)

person_skills.to_sql("PersonSkills", connection, if_exists="replace", index=False)

skills.to_sql("Skills", connection, if_exists="replace", index=False)

print("Tables Imported Successfully!")

Tables Imported Successfully!

In [16]:
query = """
SELECT name
FROM sqlite_master
WHERE type='table';
"""

pd.read_sql(query, connection)

           name
0          Jobs
1    Candidates
2  Applications
3  PersonSkills
4        Skills

In [18]:
query = """
SELECT *
FROM Jobs
LIMIT 5;
"""

pd.read_sql(query, connection)

,job_id,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent,clean_description,clean_requirements
0,1,Marketing Intern,"US, NY, New York",Marketing,None,"We're Food52, and we've created a groundbreaki...","Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,None,0,1,0,Other,Internship,None,None,Marketing,0,food52 a fastgrowing james beard awardwinning ...,experience with content management systems a m...
1,2,Customer Service - Cloud Video Production,"NZ, , Auckland",Success,None,"90 Seconds, the worlds Cloud Video Production ...",Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,0,1,0,Full-time,Not Applicable,None,Marketing and Advertising,Customer Service,0,organised focused vibrant awesomedo you have a...,what we expect from youyour key responsibility...
2,3,Commissioning Machinery Assistant (CMA),"US, IA, Wever",None,None,Valor Services provides Workforce Solutions th...,"Our client, located in Houston, is actively se...",Implement pre-commissioning and commissioning ...,None,0,1,0,None,None,None,None,None,0,our client located in houston is actively seek...,implement precommissioning and commissioning p...
3,4,Account Executive - Washington DC,"US, DC, Washington",Sales,None,Our passion for improving quality of life thro...,THE COMPANY: ESRI – Environmental Systems Rese...,"EDUCATION: Bachelor’s or Master’s in GIS, busi...",Our culture is anything but corporate—we have ...,0,1,0,Full-time,Mid-Senior level,Bachelor's Degree,Computer Software,Sales,0,the company esri environmental systems researc...,education bachelors or masters in gis business...
4,5,Bill Review Manager,"US, FL, Fort Worth",None,None,SpotSource Solutions LLC is a Global Human Cap...,JOB TITLE: Itemization Review ManagerLOCATION:...,QUALIFICATIONS:RN license in the State of Texa...,Full Benefits Offered,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Hospital & Health Care,Health Care Provider,0,job title itemization review managerlocation f...,qualificationsrn license in the state of texas...

In [20]:
cursor.execute("""

CREATE VIEW IF NOT EXISTS JobCandidateView AS

SELECT

a.application_id,

j.job_id,

j.title AS job_title,

p.person_id,

p.name

FROM Applications a

JOIN Jobs j
ON a.job_id=j.job_id

JOIN Candidates p
ON a.person_id=p.person_id;

""")

connection.commit()

print("SQL View Created Successfully!")

SQL View Created Successfully!

In [22]:
query = """
SELECT *
FROM JobCandidateView
LIMIT 10;
"""

pd.read_sql(query, connection)

,application_id,job_id,job_title,person_id,name
0,1,15796,Beauty & Fragrance consultants needed,20608,MySQL Database Administrator
1,2,861,Retail Territory Merchandiser,37600,MSSQL/MYSQL/PostgreSQL Database Administrator
2,3,5391,Inside Sales Rep,51921,Shmitt Technologies
3,4,11965,Cities Project Manager,28530,VP of Information Technology
4,5,11285,Digital Procurement Assistant,35955,Python Developer
5,6,6266,Freelance Writer,27857,Security Engineer
6,7,16851,Lawn Crew Member,2574,Junior database administrator
7,8,4427,Video and Graphics Executive Intern,12809,Toan Dang
8,9,14424,TS16 Railway Station Assistant Under NAS 16-18...,35368,NETWORK ENGINEER
9,10,11364,Android Engineer,36802,Aircraft Mechanic/ Database Administrator

In [24]:
connection.close()

print("Database Closed")

Database Closed