In [1]:
import pandas as pd
import sqlite3

In [3]:
connection = sqlite3.connect("RecruitSmart.db")

In [5]:
query = """
SELECT name
FROM sqlite_master
WHERE type='table';
"""

pd.read_sql(query, connection)

           name
0          Jobs
1    Candidates
2  Applications
3  PersonSkills
4        Skills

In [7]:
pd.read_sql("SELECT * FROM Skills LIMIT 10;", connection)

                                               skill
0                                       Mongo DB-3.2
1                                          JNDI LDAP
2                                  Stored Procedures
3                            Perform ad-hoc analysis
4  Monitored and resolved flight crew legality is...
5                                   Dashboard System
6                       Operate unit level computers
7                       Setting Up Test Environments
8                                   Write test cases
9                                   Server resources

In [9]:
pd.read_sql("SELECT * FROM PersonSkills LIMIT 10;", connection)

   person_id                    skill
0          1  Database administration
1          1                 Database
2          1            Ms sql server
3          1       Ms sql server 2005
4          1               Sql server
5          1          Sql server 2005
6          1          Sql server 2008
7          1       Sql server 2008 r2
8          1          Sql server 2012
9          1                      Sql

In [44]:
query = """

SELECT
    person_id,
    COUNT(skill) AS total_skills

FROM PersonSkills

GROUP BY person_id

ORDER BY total_skills DESC;

"""

pd.read_sql(query, connection)

       person_id  total_skills
0          54188           441
1          35877           441
2          17566           441
3          49359           433
4          31048           433
...          ...           ...
54853       2165             1
54854       2079             1
54855       1552             1
54856        669             1
54857         28             1

[54858 rows x 2 columns]

In [50]:
pd.read_sql("""
SELECT
    job_id,
    required_experience
FROM Jobs
LIMIT 10;
""", connection)

   job_id required_experience
0       1          Internship
1       2      Not Applicable
2       3                None
3       4    Mid-Senior level
4       5    Mid-Senior level
5       6                None
6       7    Mid-Senior level
7       8                None
8       9           Associate
9      10         Entry level

In [52]:
pd.read_sql("""
SELECT
    person_id,
    COUNT(*) AS duplicate_count
FROM Candidates
GROUP BY person_id
HAVING COUNT(*) > 1;
""", connection)

Empty DataFrame
Columns: [person_id, duplicate_count]
Index: []

In [54]:
pd.read_sql("""
SELECT
    application_id,
    COUNT(*) AS duplicate_count
FROM Applications
GROUP BY application_id
HAVING COUNT(*) > 1;
""", connection)

Empty DataFrame
Columns: [application_id, duplicate_count]
Index: []

In [56]:
pd.read_sql("""
SELECT
    job_id,
    required_experience
FROM Jobs
LIMIT 10;
""", connection)

   job_id required_experience
0       1          Internship
1       2      Not Applicable
2       3                None
3       4    Mid-Senior level
4       5    Mid-Senior level
5       6                None
6       7    Mid-Senior level
7       8                None
8       9           Associate
9      10         Entry level

In [58]:
query = """
SELECT
job_id,

required_experience,

CASE

WHEN required_experience='Internship' THEN 0

WHEN required_experience='Entry level' THEN 1

WHEN required_experience='Associate' THEN 2

WHEN required_experience='Mid-Senior level' THEN 3

WHEN required_experience='Executive' THEN 4

ELSE NULL

END AS experience_score

FROM Jobs

LIMIT 20;
"""

pd.read_sql(query, connection)

    job_id required_experience  experience_score
0        1          Internship               0.0
1        2      Not Applicable               NaN
2        3                None               NaN
3        4    Mid-Senior level               3.0
4        5    Mid-Senior level               3.0
5        6                None               NaN
6        7    Mid-Senior level               3.0
7        8                None               NaN
8        9           Associate               2.0
9       10         Entry level               1.0
10      11    Mid-Senior level               3.0
11      12                None               NaN
12      13           Associate               2.0
13      14      Not Applicable               NaN
14      15           Associate               2.0
15      16           Executive               4.0
16      17    Mid-Senior level               3.0
17      18                None               NaN
18      19                None               NaN
19      20                None               NaN

In [60]:
pd.read_sql("""
SELECT
person_id,
COUNT(*) AS duplicate_count
FROM Candidates
GROUP BY person_id
HAVING COUNT(*) > 1;
""", connection)

Empty DataFrame
Columns: [person_id, duplicate_count]
Index: []

In [62]:
pd.read_sql("""
SELECT
application_id,
COUNT(*) AS duplicate_count
FROM Applications
GROUP BY application_id
HAVING COUNT(*) > 1;
""", connection)

Empty DataFrame
Columns: [application_id, duplicate_count]
Index: []