In [1]:
import pandas as pd
import sqlite3

In [3]:
connection = sqlite3.connect("RecruitSmart.db")

In [5]:
query = """

SELECT
job_id,
required_experience,

CASE
WHEN required_experience='Internship' THEN 0
WHEN required_experience='Entry level' THEN 1
WHEN required_experience='Associate' THEN 2
WHEN required_experience='Mid-Senior level' THEN 3
WHEN required_experience='Executive' THEN 4
ELSE NULL
END AS experience_score,

ROUND(
(
CASE
WHEN required_experience='Internship' THEN 0
WHEN required_experience='Entry level' THEN 1
WHEN required_experience='Associate' THEN 2
WHEN required_experience='Mid-Senior level' THEN 3
WHEN required_experience='Executive' THEN 4
ELSE NULL
END
)/4.0,2) AS normalized_score

FROM Jobs

LIMIT 20;

"""

pd.read_sql(query, connection)

    job_id required_experience  experience_score  normalized_score
0        1          Internship               0.0              0.00
1        2      Not Applicable               NaN               NaN
2        3                None               NaN               NaN
3        4    Mid-Senior level               3.0              0.75
4        5    Mid-Senior level               3.0              0.75
5        6                None               NaN               NaN
6        7    Mid-Senior level               3.0              0.75
7        8                None               NaN               NaN
8        9           Associate               2.0              0.50
9       10         Entry level               1.0              0.25
10      11    Mid-Senior level               3.0              0.75
11      12                None               NaN               NaN
12      13           Associate               2.0              0.50
13      14      Not Applicable               NaN               NaN
14      15           Associate               2.0              0.50
15      16           Executive               4.0              1.00
16      17    Mid-Senior level               3.0              0.75
17      18                None               NaN               NaN
18      19                None               NaN               NaN
19      20                None               NaN               NaN

In [7]:
query = """

SELECT
job_id,
title,
requirements

FROM Jobs

WHERE

requirements LIKE '%AWS%'

OR requirements LIKE '%Azure%'

OR requirements LIKE '%Cisco%'

OR requirements LIKE '%Oracle%'

LIMIT 10;

"""

pd.read_sql(query, connection)

,job_id,title,requirements
0,26,H1B SPONSOR FOR L1/L2/OPT,"JAVA, .NET, SQL, ORACLE, SAP, Informatica, Big..."
1,31,Customer Service Technical Specialist,Qualifications:Minimum of 6 months customer se...
2,33,Craftsman Associate,Requirements: (Please do not apply if you do ...
3,172,System Administrator,Detailed knowledge of the Linux OS (RHEL ideal...
4,193,"Manager, Network Engineering",Bachelor’s Degree in Computer Science or relat...
5,205,Junior Python Developer,Skills and experienceDegree in Computer Scienc...
6,250,IT Engineer,Key requirementsExperience designing and devel...
7,386,IT Rockstar Wanted for Fun and Fast Growing Sa...,What you MUST have (IT Hobbyists and amateurs ...
8,397,IT System Engineer,"We expect from you:Be fluent in English, have ..."
9,417,ODI/ETL Developer,Your skills:University degree in Computer Scie...

In [9]:
query = """

SELECT
job_id,
title,
requirements

FROM Jobs

WHERE

requirements LIKE '%Python%'

OR requirements LIKE '%SQL%'

OR requirements LIKE '%Java%'

OR requirements LIKE '%Excel%'

OR requirements LIKE '%Machine Learning%'

LIMIT 10;

"""

pd.read_sql(query, connection)

,job_id,title,requirements
0,1,Marketing Intern,Experience with content management systems a m...
1,2,Customer Service - Cloud Video Production,What we expect from you:Your key responsibilit...
2,4,Account Executive - Washington DC,"EDUCATION: Bachelor’s or Master’s in GIS, busi..."
3,10,Customer Service Associate - Part Time,Minimum Requirements:Minimum of 6 months custo...
4,11,ASP.net Developer Job opportunity at United St...,Position : #URL_86fd830a95a64e2b30ceed829e63fd...
5,13,"Applications Developer, Digital",Requirements:4 – 5 years’ experience in develo...
6,15,Account Executive - Sydney,You’ll need to be smart and passionate and hav...
7,20,Process Controls Engineer - DCS PLC MS Office ...,Must have 5 or more years of experience with D...
8,21,Marketing Assistant,Job RequirementsAssist in creating client onli...
9,22,Front End Developer,You will most likely have:A solid mastery of m...

In [11]:
query = """

SELECT

job_id,

COUNT(*) AS frequency

FROM Jobs

GROUP BY job_id

ORDER BY frequency DESC;

"""

pd.read_sql(query, connection)

       job_id  frequency
0       17880          1
1       17879          1
2       17878          1
3       17877          1
4       17876          1
...       ...        ...
17875       5          1
17876       4          1
17877       3          1
17878       2          1
17879       1          1

[17880 rows x 2 columns]

In [13]:
query = """

SELECT

title,

COUNT(*) AS total_jobs

FROM Jobs

GROUP BY title

ORDER BY total_jobs DESC

LIMIT 20;

"""

pd.read_sql(query, connection)

                                                title  total_jobs
0                             English Teacher Abroad          311
1                         Customer Service Associate          146
2   Graduates: English Teacher Abroad (Conversatio...         144
3                              English Teacher Abroad          95
4                                   Software Engineer          86
5             English Teacher Abroad (Conversational)          83
6             Customer Service Associate - Part Time           76
7                                     Account Manager          75
8                                       Web Developer          66
9                                     Project Manager          62
10              Beauty & Fragrance consultants needed          60
11                 Graduates: English Teacher Abroad           57
12                    Customer Service Representative          51
13                           Administrative Assistant          48
14                                    Product Manager          47
15                                     Office Manager          46
16                               Sales Representative          45
17                                  Marketing Manager          45
18                         Customer Service Associate          45
19                                      iOS Developer          44

In [15]:
connection.close()

print("Database Closed Successfully!")

Database Closed Successfully!