In [4]:
import pandas as pd
import numpy as np

In [6]:
jobs = pd.read_csv(r"C:\Users\cbala\OneDrive\Desktop\RecruitSmart\data\fake_job_postings.csv")

people = pd.read_csv(r"C:\Users\cbala\OneDrive\Desktop\RecruitSmart\data\01_people.csv")

abilities = pd.read_csv(r"C:\Users\cbala\OneDrive\Desktop\RecruitSmart\data\02_abilities.csv")

education = pd.read_csv(r"C:\Users\cbala\OneDrive\Desktop\RecruitSmart\data\03_education.csv")

experience = pd.read_csv(r"C:\Users\cbala\OneDrive\Desktop\RecruitSmart\data\04_experience.csv")

person_skills = pd.read_csv(r"C:\Users\cbala\OneDrive\Desktop\RecruitSmart\data\05_person_skills.csv")

skills = pd.read_csv(r"C:\Users\cbala\OneDrive\Desktop\RecruitSmart\data\06_skills.csv")

print("✅ All datasets loaded successfully!")

✅ All datasets loaded successfully!

In [7]:
print("Jobs Dataset Shape:", jobs.shape)
print("People Dataset Shape:", people.shape)
print("Abilities Dataset Shape:", abilities.shape)
print("Education Dataset Shape:", education.shape)
print("Experience Dataset Shape:", experience.shape)
print("Person Skills Dataset Shape:", person_skills.shape)
print("Skills Dataset Shape:", skills.shape)

Jobs Dataset Shape: (17880, 18)
People Dataset Shape: (54933, 5)
Abilities Dataset Shape: (1219473, 2)
Education Dataset Shape: (75999, 5)
Experience Dataset Shape: (265404, 6)
Person Skills Dataset Shape: (2483376, 2)
Skills Dataset Shape: (226760, 1)

In [8]:
jobs.head()

,job_id,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent
0,1,Marketing Intern,"US, NY, New York",Marketing,NaN,"We're Food52, and we've created a groundbreaki...","Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,NaN,0,1,0,Other,Internship,NaN,NaN,Marketing,0
1,2,Customer Service - Cloud Video Production,"NZ, , Auckland",Success,NaN,"90 Seconds, the worlds Cloud Video Production ...",Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,0,1,0,Full-time,Not Applicable,NaN,Marketing and Advertising,Customer Service,0
2,3,Commissioning Machinery Assistant (CMA),"US, IA, Wever",NaN,NaN,Valor Services provides Workforce Solutions th...,"Our client, located in Houston, is actively se...",Implement pre-commissioning and commissioning ...,NaN,0,1,0,NaN,NaN,NaN,NaN,NaN,0
3,4,Account Executive - Washington DC,"US, DC, Washington",Sales,NaN,Our passion for improving quality of life thro...,THE COMPANY: ESRI – Environmental Systems Rese...,"EDUCATION: Bachelor’s or Master’s in GIS, busi...",Our culture is anything but corporate—we have ...,0,1,0,Full-time,Mid-Senior level,Bachelor's Degree,Computer Software,Sales,0
4,5,Bill Review Manager,"US, FL, Fort Worth",NaN,NaN,SpotSource Solutions LLC is a Global Human Cap...,JOB TITLE: Itemization Review ManagerLOCATION:...,QUALIFICATIONS:RN license in the State of Texa...,Full Benefits Offered,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Hospital & Health Care,Health Care Provider,0

In [9]:
people.head()

,person_id,name,email,phone,linkedin
0,1,Database Administrator,NaN,NaN,NaN
1,2,Database Administrator,NaN,NaN,NaN
2,3,Oracle Database Administrator,NaN,NaN,NaN
3,4,Amazon Redshift Administrator and ETL Develope...,NaN,NaN,NaN
4,5,Scrum Master Scrum Master Scrum Master,NaN,NaN,NaN

In [10]:
experience.head()

,person_id,title,firm,start_date,end_date,location
0,1,Database Administrator,Family Private Care LLC,04/2017,Present,"Roswell, GA"
1,1,Database Administrator,Incomm,01/2014,02/2017,"Alpharetta, GA"
2,2,Database Administrator,Intercontinental Registry,12/2008,08/2011,"Lagos, GU"
3,3,Oracle Database Administrator,Cognizant,06/2016,Present,"Hyderabad, Telangana"
4,3,Oracle Database Administrator,Convergys,06/2014,06/2016,"Hyderabad, Telangana"

In [11]:
print("Jobs Dataset Columns")
print(jobs.columns)

print("\nPeople Dataset Columns")
print(people.columns)

print("\nExperience Dataset Columns")
print(experience.columns)

Jobs Dataset Columns
Index(['job_id', 'title', 'location', 'department', 'salary_range',
       'company_profile', 'description', 'requirements', 'benefits',
       'telecommuting', 'has_company_logo', 'has_questions', 'employment_type',
       'required_experience', 'required_education', 'industry', 'function',
       'fraudulent'],
      dtype='object')

People Dataset Columns
Index(['person_id', 'name', 'email', 'phone', 'linkedin'], dtype='object')

Experience Dataset Columns
Index(['person_id', 'title', 'firm', 'start_date', 'end_date', 'location'], dtype='object')

In [12]:
print("Jobs Dataset Missing Values")
print(jobs.isnull().sum())

print("\nPeople Dataset Missing Values")
print(people.isnull().sum())

print("\nExperience Dataset Missing Values")
print(experience.isnull().sum())

Jobs Dataset Missing Values
job_id                     0
title                      0
location                 346
department             11547
salary_range           15012
company_profile         3308
description                1
requirements            2696
benefits                7212
telecommuting              0
has_company_logo           0
has_questions              0
employment_type         3471
required_experience     7050
required_education      8105
industry                4903
function                6455
fraudulent                 0
dtype: int64

People Dataset Missing Values
person_id        0
name           114
email        53340
phone        53100
linkedin     46395
dtype: int64

Experience Dataset Missing Values
person_id         0
title           111
firm           4203
start_date     2262
end_date       2724
location      53055
dtype: int64

In [13]:
print("Jobs Dataset")
print(jobs.info())

print("\nPeople Dataset")
print(people.info())

print("\nExperience Dataset")
print(experience.info())

Jobs Dataset
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17880 entries, 0 to 17879
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   job_id               17880 non-null  int64
 1   title                17880 non-null  object
 2   location             17534 non-null  object
 3   department           6333 non-null   object
 4   salary_range         2868 non-null   object
 5   company_profile      14572 non-null  object
 6   description          17879 non-null  object
 7   requirements         15184 non-null  object
 8   benefits             10668 non-null  object
 9   telecommuting        17880 non-null  int64
 10  has_company_logo     17880 non-null  int64
 11  has_questions        17880 non-null  int64
 12  employment_type      14409 non-null  object
 13  required_experience  10830 non-null  object
 14  required_education   9775 non-null   object
 15  industry             12977 non-null  object
 16  function             11425 non-null  object
 17  fraudulent           17880 non-null  int64
dtypes: int64(5), object(13)
memory usage: 2.5+ MB
None

People Dataset
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54933 entries, 0 to 54932
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   person_id  54933 non-null  int64
 1   name       54819 non-null  object
 2   email      1593 non-null   object
 3   phone      1833 non-null   object
 4   linkedin   8538 non-null   object
dtypes: int64(1), object(4)
memory usage: 2.1+ MB
None

Experience Dataset
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 265404 entries, 0 to 265403
Data columns (total 6 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   person_id   265404 non-null  int64
 1   title       265293 non-null  object
 2   firm        261201 non-null  object
 3   start_date  263142 non-null  object
 4   end_date    262680 non-null  object
 5   location    212349 non-null  object
dtypes: int64(1), object(5)
memory usage: 12.1+ MB
None

In [14]:
import pandas as pd
import numpy as np

# Set seed for reproducibility
np.random.seed(42)

# Create bridge table
num_applications = 1000

applications = pd.DataFrame({
    "application_id": range(1, num_applications + 1),
    "job_id": np.random.choice(jobs["job_id"], num_applications),
    "person_id": np.random.choice(people["person_id"], num_applications)
})

applications.head()

   application_id  job_id  person_id
0               1   15796      20608
1               2     861      37600
2               3    5391      51921
3               4   11965      28530
4               5   11285      35955

In [24]:
applications.to_csv(
    r"C:\Users\cbala\OneDrive\Desktop\RecruitSmart\data\applications.csv",
    index=False
)

print("Applications table saved successfully!")

Applications table saved successfully!

In [26]:
experience.isnull().sum()

person_id         0
title           111
firm           4203
start_date     2262
end_date       2724
location      53055
dtype: int64

In [28]:
experience["end_date"] = experience["end_date"].fillna("Present")

In [30]:
experience["start_date"] = experience["start_date"].fillna("Unknown")

In [32]:
experience.isnull().sum()

person_id         0
title           111
firm           4203
start_date        0
end_date          0
location      53055
dtype: int64

In [34]:
import re

In [36]:
def clean_text(text):

    if pd.isnull(text):
        return ""

    text = text.lower()

    text = re.sub(r"[^a-zA-Z0-9\s]", "", text)

    text = re.sub(r"\s+", " ", text)

    return text.strip()

In [38]:
jobs["clean_description"] = jobs["description"].apply(clean_text)

jobs["clean_requirements"] = jobs["requirements"].apply(clean_text)

In [40]:
jobs[["description", "clean_description"]].head()

,description,clean_description
0,"Food52, a fast-growing, James Beard Award-winn...",food52 a fastgrowing james beard awardwinning ...
1,Organised - Focused - Vibrant - Awesome!Do you...,organised focused vibrant awesomedo you have a...
2,"Our client, located in Houston, is actively se...",our client located in houston is actively seek...
3,THE COMPANY: ESRI – Environmental Systems Rese...,the company esri environmental systems researc...
4,JOB TITLE: Itemization Review ManagerLOCATION:...,job title itemization review managerlocation f...

In [42]:
jobs[["requirements", "clean_requirements"]].head()

,requirements,clean_requirements
0,Experience with content management systems a m...,experience with content management systems a m...
1,What we expect from you:Your key responsibilit...,what we expect from youyour key responsibility...
2,Implement pre-commissioning and commissioning ...,implement precommissioning and commissioning p...
3,"EDUCATION: Bachelor’s or Master’s in GIS, busi...",education bachelors or masters in gis business...
4,QUALIFICATIONS:RN license in the State of Texa...,qualificationsrn license in the state of texas...

In [44]:
jobs.to_csv(
    r"C:\Users\cbala\OneDrive\Desktop\RecruitSmart\data\jobs_cleaned.csv",
    index=False
)

print("Cleaned Jobs Dataset Saved!")

Cleaned Jobs Dataset Saved!